### ISSUE TITLE
Rendered Text is not functional

### ISSUE THREAD

**Issue by 00-Evan** [00-Evan/shattered-pixel-dungeon-gdx#19]
Currently there is no rendered text implementation in the GDX port. This is both holding back the quality of displayed text and also preventing translations from being displayed.

**Comment by SupaFresh** [comment]
Try looking at the commits in https://github.com/WiseClock/localized-pixel-dungeon-gdx   I think they were able to get multiple translations in their version so maybe there is a solution to the problem there.
