### ISSUE TITLE
Backpack/Indicators flicker in fullscreen

### ISSUE THREAD

**Issue by benzarr410** [00-Evan/shattered-pixel-dungeon-gdx#23]
Changed because I thought it would flair like on Reddit

**Comment by benzarr410** [comment]
Only affects in fullscreen, running .jar archive

**Comment by 00-Evan** [comment]
I'm not able to reproduce this, what is your OS, java version, and desktop resolution?

Can you include a screenshot or video?

**Comment by benzarr410** [comment]
I'm running GalliumOS 2.0, Java 8, and resolution 1366x768. Sadly I cannot include a screenshot. Fullscreen doesn't allow me to take screenshots, and I can't do it in windowed because it doesn't happen in windowed. :/

**Comment by 00-Evan** [comment]
hmm, There isn't really a way for me to reproduce this. Is there any way you can record this happening externally (e.g. with a phone) and send me that?

**Comment by benzarr410** [comment]
I don't think there will be a need for that, it fixed itself. Closing because bug was most likely not bug
