### ISSUE TITLE
Settings Screen overlaps Key bindings setup

### ISSUE THREAD

**Issue by benzarr410** [00-Evan/shattered-pixel-dungeon-gdx#24]
Display scale 4x, windowed, using the Java archive

![](http://i.imgur.com/ML0SrQp.png)

**Comment by 00-Evan** [comment]
I'm not able to reproduce this.

Does this always happen, or only after you take specific actions?

**Comment by benzarr410** [comment]
This always happens, no matter what.

**Comment by benzarr410** [comment]
WAIT I'm wrong, just tested again, and it was a one time ordeal. Closing issue because no longer an issue.
