### ISSUE TITLE
Attack Button randomly stops working.

### ISSUE THREAD

**Issue by benzarr410** [00-Evan/shattered-pixel-dungeon-gdx#26]
Sometimes, during a fight, the attack button (screenshot)
![image](https://cloud.githubusercontent.com/assets/25698061/23325761/e6d099c4-fac5-11e6-95dd-060d18a9ac6f.png) will randomly no longer do anything when clicked. It fixes itself when quitting/reloading. Running Java 8, GalliumOS 2.1beta1, v0.5.0b

**Comment by 00-Evan** [comment]
I don't think this is a desktop specific issue, but I also don't yet have any solid steps for how to reproduce this. It is in my list of stuff to investigate and fix though.
