### ISSUE TITLE
Keyboard only controls

### ISSUE THREAD

**Issue by uaBArt** [00-Evan/shattered-pixel-dungeon-gdx#27]
Is it possible to add ability to use items from backpack using keyboard? 
Mostly everything works without mouse, except this. 
I want to play by using gamepad, and configured everything except this...

**Comment by 00-Evan** [comment]
This is something that I do want to implement before a more full desktop release, but it currently isn't planned.

If/When shattered gets a more full desktop release, my plan is that it will feature full controller support.
