### ISSUE TITLE
Game doesn't open in fullscreen

### ISSUE THREAD

**Issue by BozoDel** [00-Evan/shattered-pixel-dungeon-gdx#32]
If I set the game to fullscreen and exit, I doesn't show any graphics. I can hear the music, I can Alt+Tab and see the game in the window bar, but it's as if it's transparent. I have to edit pd-prefs in order to be able to open the game again, in windowed mode.

I was running version 0.6.0b, on Linux Mint 18 MATE 64-bit. java -version gives me:

    java version "1.8.0_144"
    Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
    Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**Comment by dewstend** [comment]
> If I set the game to fullscreen and exit, I doesn't show any graphics. I can hear the music, I can Alt+Tab and see the game in the window bar, but it's as if it's transparent. I have to edit pd-prefs in order to be able to open the game again, in windowed mode.
> 
> I was running version 0.6.0b, on Linux Mint 18 MATE 64-bit. java -version gives me:
> 
> ```
> java version "1.8.0_144"
> Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
> Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
> ```

I just tested this (through recompiling again) and it didn't present such issue. Is your app packaged or are you running ./gradlew desktop:run as you close the game?

**Comment by BozoDel** [comment]
Ahm, that was a while ago. Now I'm using Mint 18.3 with Cinnamon, and I don't have the issue anymore, using either Oracle Java or OpendJDK. Maybe it was an issue with MATE.

I think I was running the .jar file downloaded from here, back then.

You can probably mark this as closed. I wouldn't know how to do that.

**Comment by 00-Evan** [comment]
this may have been incidentally fixed by updating the libgdx version. closed.
