### ISSUE TITLE
Running on Android bug

### ISSUE THREAD

**Issue by rahzell** [00-Evan/shattered-pixel-dungeon-gdx#33]
Hi, on Android 7.1.2(miui 9.2) I got a write/read exception after I start a new game or load an old save.

possible workaround:
give permission in AndroidManifest.xls:
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

**Comment by 00-Evan** [comment]
This is the place to report issues with the libGDX desktop build of the game.

You'll want to post here for android: https://github.com/00-Evan/shattered-pixel-dungeon/issues

Regardless, the game does no reading or writing to general storage, it is always to the app-specific storage location reserved for it by android, which requires no permissions to access.
