### ISSUE TITLE
Add a flag to start in landscape mode

### ISSUE THREAD

**Issue by baco** [00-Evan/shattered-pixel-dungeon-gdx#34]
When launching from CLI the `.jar` file, add some flag to start the game in landscape mode. Or at least remember the aspect ratio when exiting game.

**Comment by 00-Evan** [comment]
I'll add support for retaining screen size, should be fairly simple, and I'll be doing a v0.6.3b for android anyway.

**Comment by 00-Evan** [comment]
Afraid due to limitations in libgdx it's not simple to just have window state be saved when the game is maximized, however as of 0.6.4 the game now will remember how the window as been resized.
