### ISSUE TITLE
Murky water tiles is rendered over other tiles

### ISSUE THREAD

**Issue by dewstend** [00-Evan/shattered-pixel-dungeon-gdx#37]
![murkywaterrendered](https://user-images.githubusercontent.com/41499530/47251950-0301a100-d40a-11e8-833e-faa4cec95e64.png)

After exploring out a bit, visited non-current rooms will draw the murky water tile over all tiles and sometimes it creeps into the current room.

Tested on Xubuntu.

**Comment by 00-Evan** [comment]
Closing this issue as this repo is now deprecated and I am not planning on fixing any issues which are specific to it. Feel free to make a new issue in the main repository if you encounter this issue again.
