### ISSUE TITLE
Is the LibGDX version available for Android?

### ISSUE THREAD

**Issue by EmmanuelMess** [00-Evan/shattered-pixel-dungeon-gdx#39]
Is the LibGDX version available for Android? Compiling for android as the README says only gives the error:

> Project 'android' not found in root project 'shattered-pixel-dungeon-gdx'.

**Comment by 00-Evan** [comment]
LibGDX is capable of building to android, but it is disabled for this project. I intend to eventually move the android codebase to be universal, and will likely base it on LibGDX. Once that is done desktop/android will both build from one codebase.
