### ISSUE TITLE
Can't run the desktop version: Assertion `version->filename == NULL

### ISSUE THREAD

**Issue by Negirno** [00-Evan/shattered-pixel-dungeon-gdx#41]
I'm using the standalone (not the snap) jar version of Shattered Pixel Dungeon 0.7.1d on my desktop machine running Ubuntu 18.04. I'm using the java runtime package `jre-default`.

A week ago, the runtime refuses to run the game. It displays the following error on the console:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/path/to/ShatteredPD.Desktop.v0.7.1d.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

**Comment by 00-Evan** [comment]
From a bit of googling it seems this may be an error due to the version of your JRE: https://www.minecraftforum.net/forums/support/java-edition-support/2931149-cant-launch-on-ubuntu-18-10

This is the sort of thing that will be resolved by packaging a JRE with shattered, which I probably will do at some point.

**Comment by Negirno** [comment]
Thanks. I've installed `openjdk-8-jdk` and set it as the default java with `sudo uptdate-alternatives --config java`, and the game runs again.

**Comment by 00-Evan** [comment]
I'm closing this as this repo is no longer being maintained. Desktop builds for ShatteredPD are now made using the main repository here: https://github.com/00-Evan/shattered-pixel-dungeon

There are several structural and build-process improvements to the new desktop codebase, so this issue may be resolved there. Please feel free to make a new issue in the main repo if you're still having this problem with v0.8.0+ though.
