### ISSUE TITLE
Wrong display of `é`, `à` and `è` (and probably some other characters) as `�`

### ISSUE THREAD

**Issue by louisroyer** [00-Evan/shattered-pixel-dungeon-gdx#47]
Running [ShatteredPD.Desktop.v0.7.5f.jar](https://github.com/00-Evan/shattered-pixel-dungeon-gdx/releases/download/v0.7.5f/ShatteredPD.Desktop.v0.7.5f.jar) on debian.
```
$ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-1deb10u1, mixed mode, sharing) 
```
![2020-01-30-201632_422x634_scrot](https://user-images.githubusercontent.com/55180044/73482683-7d0b2e80-439e-11ea-89d4-4a50698b8522.png)

**Comment by 00-Evan** [comment]
Closed as you've duplicated it here: https://github.com/00-Evan/shattered-pixel-dungeon/issues/366
