### ISSUE TITLE
Journal button keeps blinking after pressing keyboard shortcut key 

### ISSUE THREAD

**Issue by LyraLover228** [00-Evan/shattered-pixel-dungeon-gdx#48]
Version: 0.7.5e GDX

Steps to reproduce:
1. Pick up guidebook page or alchemy book page 
2. Press journal shortcut button

The button stops blinking after being pressed, though.

**Comment by 00-Evan** [comment]
This repo is now deprecated, and this bug is already incidentally fixed in the new universal repo here: https://github.com/00-Evan/shattered-pixel-dungeon

Starting with the next update the standard desktop builds will be coming from that new repo.
